import axios from 'axios';
import Header from 'components/headerComponents';
import Navbar from 'components/navbarComponents';
import Results from 'components/resultsComponents';
import Head from 'next/head';
import requests from 'utils/requests';

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>IMDB-Clone App</title>
        <meta
          name="description"
          content="Generated by Mohammad Hadi - imdb clone - movies - series"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Section */}
      <div className="bg-gray-700">
        <Header />
      </div>

      {/* Navbar Section */}
      <Navbar />

      {/* Results Section */}
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps({ query }) {
  const { genre } = query;
  const qryTerm = requests[genre]?.url || requests['fetchTrending'].url;
  const {
    data: { results },
  } = await axios.get(`https://api.themoviedb.org/3${qryTerm}`);

  return {
    props: {
      results,
    },
  };
}
